### ISSUE TITLE
Local compilation

### ISSUE THREAD

**Issue by 1094093288** [ProtonMail/ios-mail#7] opened 2019-11-06 08:28 UTC
Can I clone the project successfully compiled with XCode11.2 locally? Follow the prompts to run the project，I am getting the following error when compiling:
No such module 'EllipticCurveKeyPair' BioProtection.swift and
Command CompileSwift failed with a nonzero exit code

**Comment by 1094093288** [comment] 2019-11-06 08:35
> Can I clone the project successfully compiled with XCode locally? I am getting the following error when compiling:
> No such module 'EllipticCurveKeyPair' BioProtection.swift and
> Command CompileSwift failed with a nonzero exit code

**Comment by 1094093288** [comment] 2019-11-06 08:53
> Can I clone the project successfully compiled with XCode11.2 locally? Follow the prompts to run the project，I am getting the following error when compiling:
> No such module 'EllipticCurveKeyPair' BioProtection.swift and
> Command CompileSwift failed with a nonzero exit code

**Comment by mackuba** [comment] 2019-11-07 20:55
Did you open the project through `.xcworkspace`? The `EllipticCurveKeyPair` module seems to come from a CocoaPod included in the repo.

**Comment by 1094093288** [comment] 2019-11-08 07:20
> Did you open the project through `.xcworkspace`? The `EllipticCurveKeyPair` module seems to come from a CocoaPod included in the repo.

Thank you very much for your answer, it works, but it has encountered new problems:
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_FLAnimatedImageView", referenced from:
      type metadata for DKPhotoGallery.DKPhotoImageView in DKPhotoImageView.o
  "_OBJC_METACLASS_$_FLAnimatedImageView", referenced from:
      _OBJC_METACLASS_$__TtC14DKPhotoGallery16DKPhotoImageView in DKPhotoImageView.o
  "_OBJC_CLASS_$_FLAnimatedImage", referenced from:
      objc-class-ref in DKPhotoBaseImagePreviewVC.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Is it what I forgot?

**Comment by 1094093288** [comment] 2019-11-08 08:11
> Did you open the project through `.xcworkspace`? The `EllipticCurveKeyPair` module seems to come from a CocoaPod included in the repo.

Thank you very much for your answer, the problem has been solved, but there has been a new problem:
error: "ProtonMail" requires a provisioning profile with the App Groups, In-App Purchase, Siri, iCloud, and Push Notifications features. Select a provisioning profile in the Signing & Capabilities editor. (in target 'ProtonMail' from project 'ProtonMail')
Is it I what forgot?

**Comment by mackuba** [comment] 2019-11-08 13:37
They use manual certificate/provisioning setup, so Xcode expects all required certificates & provisioning profiles to be there in your developer account (for the given app ID). The problem is that you can't even create them for that app ID, because this ID is assigned to ProtonMail's account. So you need to come up with some other, like if you created your own app (I used eu.mackuba.ProtonMail), and replace the "ch.protonmail.protonmail" in all relevant targets (ProtonMail, Share, Push, PushService and Siri, leave the ".Share" etc. suffixes for each target). You probably also need to update the ID in the same way in App Groups and Keychain Sharing sections. And of course choose your team in the Team selector.

And then you either create all provisioning profiles manually, or just turn on automatic provisioning in all these targets like I did :)

I also had to update the IDs and my team identifier (the one which is now "2SB5Z68H26") in `KeychainWrapper.swift` and in `ProtonMailCommon/Constants/App.swift`.

**Comment by zhj4478** [comment] 2019-11-08 19:16
@mackuba, thank you for that. it is exactly what you said.
we will try to update the readme and put this in the setup section.

**Closed by zhj4478** 2019-11-08 19:16 UTC
